version: "3.8"

services:

  frontend:
    build: ./app/frontend
    # Only needed in development, to reload vue
    volumes:
      - ./app/frontend:/app
    ports:
      - 8001:8080
    restart: always

  backend:
    build: ./app/backend
    volumes:
      - type: volume
        source: product_images
        target: /app/product_images
      # Only needed in development, to reload fastapi
      - ./app/backend:/app
    links:
      - db
    ports:
      - 3001:3030
    env_file:
      - .env
    environment:
      - PORT=3030
    depends_on:
      db:
        condition: service_healthy
    restart: always
    # Only needed in development, to reload fastapi
    command: /start-reload.sh

  db:
    build: ./app/db
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "/usr/local/bin/waitForMySQL.sh" ]
      interval: 10s
      timeout: 20s
      retries: 25
      start_period: 120s
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8383:80
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always


volumes:
  db_data:
  product_images:
