version: "3"

services:

  # frontend:
  #   build: ./app/frontend

  backend:
    build: ./app/backend
    volumes:
      - ./app/backend:/app
    links:
      - db
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: /start-reload.sh

  db:
    image: mysql
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 20s


volumes:
  db_data:
